Repository circleci/circleci-docs, pull requests merged in 2018-10, with the labels that each got.

#2726 Migrate 1.0 CI/CD with Python and revise 2.0 Python language guide
  jekyll/_cci2/language-python.md
Labels: incorrect, undocumented

#2776 Migrate ECS/ECR document
  jekyll/_cci2/deployment-integrations.md
  jekyll/_cci2/ecs-ecr.md
  jekyll/_data/sidenav.yml
Labels: undocumented

#2804 lint and typos for monitoring
  jekyll/_cci2/monitoring.md
Labels: typo
