Repository circleci/circleci-docs, pull requests merged in 2018-08, with the labels that each got.

#2537 remove warning about NDK
  jekyll/_cci2/language-android.md
Labels: inconsistent

#2538 remove incorrect run step from elixir sample config
  jekyll/_cci2/language-elixir.md
Labels: inconsistent, incorrect

#2557 Fix deprecated jest junit instructions
  jekyll/_cci2/collect-test-data.md
Labels: incorrect

#2556 prevent false start of postgres server
  jekyll/_cci2/postgres-config.md
Labels: incorrect

#2550 Migrate Testing with Firebase Test Lab to 2.0 docs
  jekyll/_cci2/google-auth.md
  jekyll/_cci2/language-android.md
Labels: undocumented

#2563 fixed typo in currently
  jekyll/_cci2/building-docker-images.md
Labels: typo

#2555 Fix incorrect information in sauce labs config
  jekyll/_cci2/browser-testing.md
Labels: incorrect

#2565 Migration improvements
  jekyll/_cci2/migration-intro.md
  jekyll/_cci2/migration.md
Labels: undocumented

#2532 Clarify transitive dependencies and clean up tag filter section
  jekyll/_cci2/configuration-reference.md
  jekyll/_cci2/env-vars.md
  jekyll/_cci2/workflows-overview.md
  jekyll/_cci2/workflows.md
Labels: inconsistent, incorrect, unclear

#2573 Clarify which ruby images are used
  jekyll/_cci2/language-android.md
  jekyll/_cci2/language-ruby.md
Labels: incorrect, unclear

#2587 Correct typos related to environment variables
  jekyll/_cci2/env-vars.md
Labels: typo, unclear

#2583 remove newlines from all templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/grammatical_error.md
  .github/ISSUE_TEMPLATE/inconsistent.md
  .github/ISSUE_TEMPLATE/incorrect.md
  .github/ISSUE_TEMPLATE/typo.md
  .github/ISSUE_TEMPLATE/unclear.md
  .github/ISSUE_TEMPLATE/undocumented.md
  pull_request_template.md
Labels: typo

#2592 add note about job time limit
  jekyll/_cci2/configuration-reference.md
Labels: undocumented

#2560 Document env vars in parallelism docs
  jekyll/_cci2/parallelism-faster-jobs.md
Labels: undocumented

#2598 Clarify server troubleshooting doc and remind people of Workflows tab
  jekyll/_cci2/faq.md
  jekyll/_cci2/troubleshooting.md
Labels: unclear

#2597 Document ordering info for api lists
  jekyll/_api/v1-reference.md
  jekyll/_data/api.yml
Labels: undocumented

#2618 Add files via upload
  jekyll/assets/img/docs/arch.png
  jekyll/assets/img/docs/migrate.png
Labels: undocumented

#2620 Container name in docs incorrect
  jekyll/_cci2/usage-statistics.md
Labels: typo

#2621 Remove redundant 'Context' section
  pull_request_template.md
Labels: unclear

#2619 Migrate OOM doc and blog post
  jekyll/_cci2/java-oom.md
  jekyll/_cci2/language-android.md
  jekyll/_cci2/language-java.md
Labels: undocumented

#2625 Clarify machine user usage
  jekyll/_cci2/gh-bb-integration.md
Labels: unclear

#2629 fix typo
  jekyll/_cci2/gh-bb-integration.md
Labels: typo

#2627 Clarify how circle changes docker
  jekyll/_cci2/custom-images.md
Labels: inconsistent, unclear

#2635 Add question about code access to faq
  jekyll/_cci2/faq.md
Labels: undocumented

#2642 add jekyll cache and alphabetize
  .gitignore
Labels: bug

#2633 Update oss.md
  jekyll/_cci2/oss.md
Labels: incorrect

#2646 Clarify google service account doc
  jekyll/_cci2/google-auth.md
Labels: unclear

#2648 Make checkout ssh key req more explicit
  jekyll/_cci2/ssh-access-jobs.md
Labels: unclear

#2656 Update sign up copy
  jekyll/_cci2/first-steps.md
Labels: unclear
