Repository circleci/circleci-docs, pull requests merged in 2018-04, with the labels that each got.

#2210 Add public repos to tutorials index doc
  jekyll/_cci2/tutorials.md
Labels: Undocumented

#2211 Clarify project level env vars
  jekyll/_cci2/env-vars.md
Labels: Clarification

#2213 Revise interpolation workaround
  jekyll/_cci2/env-vars.md
  jekyll/_cci2/migrating-from-1-2.md
Labels: Clarification

#2215 Xcode 9.3 GM
  jekyll/_cci2/testing-ios.md
Labels: Update

#2216 link to issues workflow wiki page
  CONTRIBUTING.md
Labels: Undocumented

#2217 add link to wiki page in footer
  jekyll/_includes/edit-on-github.html
Labels: Update

#2218 Examples page
  jekyll/_cci2/examples.md
  jekyll/_includes/sidebar.html
  jekyll/index.html
Labels: Undocumented

#2222 Update ios-tutorial.md
  jekyll/_cci2/ios-tutorial.md
Labels: Clarification

#2225 fix yaml syntax formatting
  jekyll/_cci2/postgres-config.md
Labels: Correction

#2226 add go app to postgres db doc
  jekyll/_cci2/postgres-config.md
Labels: Undocumented

#2230 fix breadcrumb link to basics landing page
  jekyll/_cci2/concepts.md
Labels: Correction

#2237 Revise "Scheduled Workflow" documentation
  jekyll/_cci2/workflows.md
Labels: Clarification, Correction, Inconsistency

#2243 Add link to Style Guide in wiki
  CONTRIBUTING.md
Labels: Update

#2245 Add storage space reqs for services box
  jekyll/_cci2/non-aws.md
Labels: Clarification, Update

#2251 Usage queue vs run queue
  jekyll/_cci2/faq.md
Labels: Clarification

#2247 comment example, add punctuation to python lang guide
  jekyll/_cci2/language-python.md
Labels: Clarification

#2248 add comments to ruby example, make active, remove we/our
  jekyll/_cci2/language-ruby.md
Labels: Clarification

#2252 Update deployment-integrations.md
  jekyll/_cci2/deployment-integrations.md
Labels: Undocumented

#2260 add group membership/object class to auth doc
  jekyll/_cci2/authentication.md
Labels: Update

#2256 Update high-availability.md
  jekyll/_cci2/high-availability.md
Labels: Undocumented

#2265 Update high-availability.md
  jekyll/_cci2/high-availability.md
Labels: Clarification

#2258 Add note about `setup_circle_ci`
  jekyll/_cci2/ios-codesigning.md
Labels: Clarification

#2270 Document auto cancellation of redundant builds
  jekyll/_cci2/basics.md
  jekyll/_cci2/skip-build.md
Labels: Undocumented

#2264 Document shell scripting best practices
  jekyll/_cci2/basics.md
  jekyll/_cci2/configuration-reference.md
  jekyll/_cci2/using-shell-scripts.md
Labels: Undocumented

#2274 New database doc
  jekyll/_cci2/databases.md
  jekyll/_cci2/examples.md
  jekyll/_cci2/postgres-config.md
  jekyll/_cci2/test.md
Labels: Correction

#2279 Document that build artifact URLs are encoded
  jekyll/_cci2/artifacts.md
Labels: Undocumented

#2273 add note about base64 encoding of multiline env vars
  jekyll/_cci2/env-vars.md
Labels: Undocumented

#2275 Migration landing page
  jekyll/_cci2/basics.md
  jekyll/_cci2/examples.md
  jekyll/_cci2/migrating-cloud-server.md
  jekyll/_cci2/migration.md
  jekyll/_cci2/test.md
  jekyll/_includes/sidebar.html
Labels: Undocumented

#2293 Remove more complex heroku deployment example
  jekyll/_cci2/deployment-integrations.md
Labels: Clarification, Correction

#2299 remove link to discuss
  jekyll/_includes/edit-on-github.html
Labels: Update
