Repository circleci/circleci-docs, pull requests merged in 2018-07, with the labels that each got.

#2464 Update configuration.md
  jekyll/_cci1/configuration.md
Labels: Unclear

#2473 Improved instruction on how to define Regexes for branch filters
  jekyll/_cci2/configuration-reference.md
Labels: unclear

#2475 fix yaml example indentation
  jekyll/_cci2/google-auth.md
Labels: incorrect

#2476 added cloud foundry to deployment docs
  jekyll/_cci2/deployment-integrations.md
Labels: undocumented

#2469 Split issue template by issue type
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/grammatical_error.md
  .github/ISSUE_TEMPLATE/inconsistency.md
  .github/ISSUE_TEMPLATE/incorrect.md
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/ISSUE_TEMPLATE/typo.md
  .github/ISSUE_TEMPLATE/unclear.md
  .github/ISSUE_TEMPLATE/undocumented.md
Labels: unclear

#2477 porting artifactory from 1.0 docs
  jekyll/_cci2/artifactory.md
  jekyll/_cci2/test.md
Labels: undocumented

#2479 Base checksum on package-lock.json
  jekyll/_cci2/caching.md
Labels: inconsistency

#2482 Add quotes around globbing example for consistency
  jekyll/_cci2/parallelism-faster-jobs.md
Labels: inconsistent

#2467 Adding LogDNA into the List of Logging Providers
  jekyll/_cci2/monitoring.md
  jekyll/_ccie/logging.md
Labels: undocumented

#2435 Update junit location
  jekyll/_cci2/language-elixir.md
Labels: incorrect

#2491 turn list of example logging appliances into proper list
  jekyll/_cci2/monitoring.md
Labels: grammatical error, unclear

#2490 Update browser-testing.md
  jekyll/_cci2/browser-testing.md
Labels: incorrect

#2486 remove relative path limitation
  jekyll/_cci2/local-cli.md
Labels: incorrect

#2497 small quality of life improvement for PR template
  pull_request_template.md
Labels: unclear

#2501 Update configuration.md
  jekyll/_cci1/configuration.md
Labels: typo

#2488 Revise document for better structure and explanation of image tags
  jekyll/_cci2/circleci-images.md
  jekyll/_cci2/faq.md
Labels: inconsistent, incorrect, unclear

#2508 specify what kind of problem is reportable
  jekyll/_includes/edit-on-github.html
Labels: unclear

#2480 Document required dockerfile label
  jekyll/_cci2/custom-images.md
Labels: grammatical error, incorrect, unclear, undocumented

#2515 Fix dead link to telegraf documents
  jekyll/_cci2/monitoring.md
Labels: incorrect

#2518 Update non-aws.md
  jekyll/_cci2/non-aws.md
Labels: grammatical error, typo, unclear

#2520 add note about interpolation to built-in env vars section
  jekyll/_cci2/env-vars.md
Labels: unclear, undocumented

#2513 Clarify how to download all artifacts for a build
  jekyll/_cci2/artifacts.md
Labels: unclear

#2531 Update non-aws.md
  jekyll/_cci2/non-aws.md
Labels: unclear

#2527 Document that docker-compose is pre-installed
  jekyll/_cci2/docker-compose.md
Labels: unclear

#2534 Document env vars security
  jekyll/_cci2/env-vars.md
  jekyll/_cci2/security.md
Labels: undocumented
