Repository circleci/circleci-docs, pull requests merged in 2018-05, with the labels that each got.

#2286 Update caching.md: "Using a Lock File" section
  jekyll/_cci2/caching.md
Labels: Correction

#2301 One-liner to fix a broken link
  jekyll/_cci2/databases.md
Labels: Bug

#2300 add example of base64 encoding/decoding
  jekyll/_cci2/env-vars.md
Labels: Clarification

#2306 Update Jekyll to v3.8.1.
  Gemfile
  Gemfile.lock
  docker-compose.yml
Labels: Update

#2313 fix typo in aws.md
  jekyll/_cci2/aws.md
Labels: Correction

#2305 Removes the need for any user input in the installation commands
  jekyll/_cci2/gpu.md
Labels: Update

#2318 Do not install the CLI tool in a Docker container
  jekyll/_cci2/parallelism-faster-jobs.md
Labels: Clarification

#2315 Update project walkthrough heroku example
  jekyll/_cci2/project-walkthrough.md
Labels: Update

#2337 simplify heroku deploy command
  jekyll/_cci2/deployment-integrations.md
  jekyll/_cci2/sample-config.md
Labels: Update

#2338 add name parameter to both steps
  jekyll/_cci2/configuration-reference.md
Labels: Undocumented

#2342 Add resources to macos
  jekyll/_cci2/executor-types.md
Labels: Clarification

#2343 Update google-auth.md
  jekyll/_cci2/google-auth.md
Labels: Correction

#2341 Add ssh deploy example
  jekyll/_cci2/deployment-integrations.md
Labels: Undocumented

#2344 remove LABELS.md
  LABELS.md
Labels: Outdated

#2349 Update deployment guide
  jekyll/_cci2/deployment-integrations.md
Labels: Incorrect

#2336 Add links to docker get started
  jekyll/_cci2/building-docker-images.md
  jekyll/_cci2/circleci-images.md
  jekyll/_cci2/docker-compose.md
  jekyll/_cci2/examples.md
  jekyll/_cci2/executor-types.md
  jekyll/_cci2/index.md
  jekyll/_cci2/migrating-from-1-2.md
Labels: Outdated

#2350 Edited Step #2 on Adding SSH key to CircleCI page
  jekyll/_cci2/add-ssh-key.md
Labels: Incorrect

#2354 Update monitoring.md
  jekyll/_cci2/monitoring.md
Labels: Outdated

#2345 update CIRCLE_INTERNAL_TASK_DATA value and location
  jekyll/_cci2/parallelism-faster-jobs.md
Labels: Incorrect

#2356 Added option to run jobs other than the default build
  jekyll/_cci2/local-cli.md
Labels: Undocumented

#2358 clean up copy following contribution
  jekyll/_cci2/local-cli.md
Labels: Typo

#2360 Update circleci-images.md
  jekyll/_cci2/circleci-images.md
Labels: Unclear

#2352 Document API Tokens and Scopes
  jekyll/_cci2/basics.md
  jekyll/_cci2/managing-api-tokens.md
Labels: Undocumented

#2362 add warning to use environment variables in scripts
  jekyll/_cci2/deployment-integrations.md
  jekyll/_cci2/env-vars.md
Labels: Inconsistent, Unclear

#2365 Clarify timing data requirements and document manual edits
  jekyll/_cci2/faq.md
  jekyll/_cci2/parallelism-faster-jobs.md
  jekyll/_cci2/test.md
Labels: Inconsistent, Unclear

#2375 Bb user key images
  jekyll/_cci2/gh-bb-integration.md
Labels: Unclear
