Repository circleci/circleci-docs, pull requests merged in 2018-03, with the labels that each got.

#2096 Fix link in elixir docs
  jekyll/_cci2/language-elixir.md
Labels: Bug

#2049 Create browser-testing.md
  jekyll/_cci2/browser-testing.md
  jekyll/_cci2/test.md
Labels: Undocumented

#2115 update caching to make it more clear
  jekyll/_cci2/caching.md
Labels: Clarification

#2123 Some updates and consistency for Workflows
  jekyll/_cci2/workflows.md
Labels: Inconsistency

#2127 Add xcode 9.2 docs for 1.0
  jekyll/_cci1/build-image-macos.md
Labels: Undocumented

#2128 Revise documentation of bad UID remapping error
  jekyll/_cci2/high-uid-error.md
  jekyll/_cci2/reference.md
Labels: Clarification

#2130 add link to example image
  jekyll/_cci2/high-uid-error.md
Labels: Clarification

#2124 Note 1 and 2 small tweaks
  jekyll/_cci2/artifacts.md
Labels: Clarification

#2142 Google Container Engine clarifications
  jekyll/_cci2/google-auth.md
  jekyll/_cci2/google-container-engine.md
Labels: Clarification

#2111 Add guide on building snap packages with CircleCI.
  jekyll/_cci2/build-publish-snap-packages.md
Labels: Undocumented

#2148 add info about ssh login shell
  jekyll/_cci2/ssh-access-jobs.md
Labels: Clarification, Undocumented

#2146 Update config ref for machine and dlc
  jekyll/_cci2/configuration-reference.md
  jekyll/_cci2/executor-types.md
Labels: Inconsistency

#2153 Explicitly mention test runner used in example
  jekyll/_cci2/project-walkthrough.md
Labels: Clarification

#2147 Env vars update
  jekyll/_cci2/contexts.md
  jekyll/_cci2/deployment-integrations.md
  jekyll/_cci2/env-vars.md
Labels: Clarification, Undocumented

#2165 Add preferred table markdown styling
  CONTRIBUTING.md
Labels: Undocumented

#2172 add note to single box instructions for oauth app URLs
  jekyll/_cci2/single-box.md
Labels: Undocumented

#2171 update ios codesigning with note about changes
  jekyll/_cci2/ios-codesigning.md
Labels: Clarification

#2164 Document differences between GitHub and Bitbucket user key creation
  jekyll/_cci2/gh-bb-integration.md
Labels: Undocumented

#2176 add yaml alias info to workflows doc
  jekyll/_cci2/workflows.md
Labels: Undocumented

#2178 Add context to Bitbucket user key workaround
  jekyll/_cci2/gh-bb-integration.md
Labels: Undocumented

#2173 Update docker-layer-caching.md
  jekyll/_cci2/docker-layer-caching.md
Labels: Update

#2177 Create certificates.md
  jekyll/_cci2/certificates.md
  jekyll/_cci2/troubleshooting.md
  jekyll/_includes/sidebar.html
Labels: Undocumented

#2170 Concepts draft
  jekyll/_cci2/basics.md
  jekyll/_cci2/concepts.md
Labels: Undocumented

#2182 Iynere workflows failed jobs patch
  jekyll/_cci2/workflows.md
  jekyll/assets/img/docs/rerun failed jobs.png
Labels: Update

#2188 Add support center link to support page
  jekyll/_cci2/help-and-support.md
Labels: Update

#2191 Add explicit inclusion of home env var
  jekyll/_cci2/contexts.md
  jekyll/_cci2/env-vars.md
Labels: Clarification

#2195 JSON key should not be encoded
  jekyll/_cci2/google-auth.md
  jekyll/_cci2/google-container-engine.md
Labels: Correction

#2196 Add note on reordering UI tests for timeouts
  jekyll/_cci2/testing-ios.md
Labels: Update

#2190 Update list of required psql databases
  jekyll/_cci2/high-availability.md
Labels: Correction

#2197 Remove breaking component manager
  jekyll/_cci2/google-auth.md
  jekyll/_cci2/google-container-engine.md
Labels: Correction

#2192 Added limitation and workaround for interpolating environment variables
  jekyll/_cci2/env-vars.md
Labels: Clarification

#2198 Replace interpolation workaround with simpler one
  jekyll/_cci2/env-vars.md
Labels: Clarification

#2201 Flesh out details of ubuntu window manager
  jekyll/_cci2/browser-testing.md
Labels: Undocumented

#2189 Clarify how split tests are run
  jekyll/_cci2/faq.md
  jekyll/_cci2/parallelism-faster-jobs.md
Labels: Clarification, Inconsistency
