Repository circleci/circleci-docs, pull requests merged in 2018-09, with the labels that each got.

#2674 Add build proc to nav
  jekyll/_data/sidenav.yml
Labels: undocumented

#2671 Clarify machine executor section
  jekyll/_cci2/executor-types.md
Labels: unclear

#2672 Change cache folder
  jekyll/_cci2/language-go.md
Labels: incorrect

#2526 Add custom ca cert info
  jekyll/_cci2/certificates.md
  jekyll/_cci2/single-box.md
Labels: undocumented

#2700 Update local-cli.md
  jekyll/_cci2/local-cli.md
Labels: undocumented

#2767 fix android guide link
  jekyll/_cci2/demo-apps.md
Labels: undocumented

#2768 add clarification around running tests
  jekyll/_cci2/parallelism-faster-jobs.md
Labels: unclear
