Repository circleci/circleci-docs, pull requests merged in 2018-06, with the labels that each got.

#2380 Move scala guide to correct directory
  jekyll/_cci2/language-scala.md
  jekyll/_cci2/tutorials.md
Labels: Undocumented

#2382 Update caching.md
  jekyll/_cci2/caching.md
Labels: Outdated

#2376 Document yaml multi merge
  jekyll/_cci2/basics.md
  jekyll/_cci2/writing-yaml.md
Labels: Undocumented

#2384 Remove duplicate env var section
  jekyll/_cci2/migrating-from-1-2.md
Labels: Inconsistent

#2394 Fix inconsistent config ref naming
  jekyll/_cci2/browser-testing.md
  jekyll/_cci2/caching.md
  jekyll/_cci2/configuration-reference.md
  jekyll/_cci2/containers.md
  jekyll/_cci2/executor-types.md
  jekyll/_cci2/hello-world.md
  jekyll/_cci2/index.md
  jekyll/_cci2/ios-migrating-from-1-2.md
  jekyll/_cci2/language-python.md
  jekyll/_cci2/migrating-from-1-2.md
  jekyll/_cci2/parallelism-faster-jobs.md
  jekyll/_cci2/reference.md
  jekyll/_cci2/test.md
  jekyll/_cci2/testing-ios.md
  jekyll/_cci2/workflows.md
Labels: Inconsistent

#2390 Add notes about jobs being triggered using the API
  jekyll/_cci2/api-job-trigger.md
Labels: Unclear

#2395 Revise notes on api job trigger example
  jekyll/_cci2/api-job-trigger.md
Labels: Inconsistent, Unclear

#2400 Reformat builtin env vars as table
  jekyll/_cci2/contexts.md
  jekyll/_cci2/databases.md
  jekyll/_cci2/env-vars.md
Labels: Unclear

#2403 Correct CIRCLECI environment variable name typo
  jekyll/_cci2/env-vars.md
Labels: Incorrect

#2404 Update Jekyll to v3.8.3 and HTML Proofer to latest release.
  Gemfile
  Gemfile.lock
  docker-compose.yml
Labels: Outdated

#2393 divide supported releases into stable/edge categories
  jekyll/_cci2/building-docker-images.md
Labels: Unclear

#2402 Point to new api permissions doc
  jekyll/_cci2/artifacts.md
  jekyll/_cci2/config-translation.md
  jekyll/_cci2/env-vars.md
  jekyll/_cci2/examples.md
  jekyll/_cci2/status-badges.md
Labels: Inconsistent

#2408 Update proxy.md
  jekyll/_cci2/proxy.md
Labels: Inconsistent

#2413 If cache matches lockfile, branch is irrelevant
  jekyll/_cci2/language-elixir.md
Labels: Outdated

#2406 Metrics forwarding
  jekyll/_cci2/monitoring.md
  jekyll/assets/img/docs/enable_metrics1.png
  jekyll/assets/img/docs/enable_metrics2.png
  jekyll/assets/img/docs/enable_metrics3a.png
  jekyll/assets/img/docs/enable_metrics3b.png
Labels: Undocumented

#2405 Usage Statistics Draft
  jekyll/_cci2/usage-statistics.md
  jekyll/assets/img/docs/usage-statistics-setting.png
Labels: Undocumented

#2417 Usage Statistics page had a missing row in first table and typo
  jekyll/_cci2/usage-statistics.md
Labels: Typo

#2412 Swap build to job
  jekyll/_cci2/artifacts.md
  jekyll/_cci2/authentication.md
  jekyll/_cci2/browser-testing.md
  jekyll/_cci2/building-docker-images.md
  jekyll/_cci2/collect-test-data.md
  jekyll/_cci2/concepts.md
  jekyll/_cci2/configuration-reference.md
  jekyll/_cci2/deployment-integrations.md
  jekyll/_cci2/env-vars.md
  jekyll/_cci2/executor-types.md
  jekyll/_cci2/faq.md
  jekyll/_cci2/hello-world.md
  jekyll/_cci2/index.md
  jekyll/_cci2/ios-migrating-from-1-2.md
  jekyll/_cci2/language-android.md
  jekyll/_cci2/language-go.md
  jekyll/_cci2/language-javascript.md
  jekyll/_cci2/language-php.md
  jekyll/_cci2/language-ruby.md
  jekyll/_cci2/migrating-from-1-2.md
  jekyll/_cci2/project-walkthrough.md
  jekyll/_cci2/sample-config.md
  jekyll/_cci2/security.md
  jekyll/_cci2/skip-build.md
  jekyll/_cci2/ssh-access-jobs.md
  jekyll/_cci2/testing-ios.md
  jekyll/_cci2/troubleshooting.md
  jekyll/_cci2/workflows-not-starting.md
  jekyll/_cci2/workflows.md
Labels: Outdated

#2419 clarify that 3 env vars are only for forked PRs
  jekyll/_cci2/env-vars.md
Labels: Incorrect

#2420 Removed copy/paste error.
  jekyll/_cci2/proxy.md
Labels: Incorrect

#2421 Fixed slight copy and paste error
  jekyll/_cci2/non-aws.md
Labels: Incorrect

#2423 distinguish between different API tokens
  jekyll/_cci2/api-job-trigger.md
Labels: Inconsistent

#2422 Clarify ambiguities in caching doc
  jekyll/_cci2/caching.md
Labels: Unclear

#2418 Migrate forked PR build security info
  jekyll/_cci2/oss.md
  jekyll/_data/categories.yml
Labels: Outdated, Undocumented

#2428 Update AWS Deploy doc for 1.0 EOL
  jekyll/_cci2/deployment-integrations.md
Labels: Incorrect, Outdated

#2430 Fix typo within migration from 1 to 2
  jekyll/_cci2/migrating-from-1-2.md
Labels: Typo

#2431 Migrate VCS permissions blurb to 2.0
  jekyll/_cci2/gh-bb-integration.md
Labels: Undocumented

#2440 Correct flipped instructions
  jekyll/_cci2/oss.md
Labels: Incorrect

#2438 add C++ open source example
  jekyll/_cci2/examples.md
Labels: Undocumented

#2446 Fix broken link
  jekyll/_cci1/faq.md
Labels: Bug

#2448 Link to CircleCI Docs configuration file in workspaces section
  jekyll/_cci2/workflows.md
Labels: Unclear

#2447 Use AWS Docker image for deployment.
  .circleci/config.yml
Labels: Outdated

#2441 DRAFT Uniqueness account level sub-bullet to context
  jekyll/_cci2/contexts.md
Labels: Undocumented

#2456 Update faq.md
  jekyll/_cci2/faq.md
Labels: Inconsistent

#2459 Fix typo in proxy.md
  jekyll/_cci2/proxy.md
Labels: Incorrect

#2454 Dlc update
  jekyll/_cci2/configuration-reference.md
  jekyll/_cci2/docker-layer-caching.md
Labels: Support

#2453 Update caching best practices for specific dependency managers
  jekyll/_cci2/caching.md
Labels: Undocumented

#2452 Update yarn cache to be more reliable
  jekyll/_cci2/yarn.md
Labels: Outdated

#2463 Clarify that the add_ssh_keys step is more necessary than you think
  jekyll/_cci2/add-ssh-key.md
  jekyll/_cci2/configuration-reference.md
Labels: Unclear
