Repository circleci/circleci-docs, pull requests merged in 2019-05, with the labels that each got.

#3372 add warning about cache sizes
  jekyll/_cci2/caching.md
Labels: undocumented

#3382 update some images and mention server customers
  jekyll/_cci2/getting-started.md
  jekyll/assets/img/docs/CircleCI-2.0-start-building.png
  jekyll/assets/img/docs/CircleCI-add-new-project-list.png
  jekyll/assets/img/docs/inside-workflows-circle-101-running.png
  jekyll/assets/img/docs/workflows-circle-101-running.png
Labels: inconsistent

#3378 fix japanese typo in env-vars.md
  jekyll/_cci2_ja/env-vars.md
Labels: typo
