Repository circleci/circleci-docs, pull requests merged in 2020-02, with the labels that each got.

#4074 [WIP][DO NOT MERGE][RE-294] First Draft of 2.19.0 Nomad Client Update Doc
  jekyll/_cci2/nomad-metrics.adoc
  jekyll/_ccie/update-nomad-clients-2190.md
Labels: Server Release 2.19

#4057 Switch to use correct terms for concurrency and parallelism
  jekyll/_cci2/api-job-trigger.md
  jekyll/_cci2/build-publish-snap-packages.md
  jekyll/_cci2/code-coverage.md
  jekyll/_cci2/concepts.md
  jekyll/_cci2/config-intro.md
  jekyll/_cci2/configuration-reference.md
  jekyll/_cci2/containers.md
  jekyll/_cci2/databases.md
  jekyll/_cci2/docker-layer-caching.md
  jekyll/_cci2/example-configs.md
  jekyll/_cci2/getting-started.md
  jekyll/_cci2/hello-world-macos.md
  jekyll/_cci2/hello-world-windows.md
  jekyll/_cci2/hello-world.md
  jekyll/_cci2/insights.md
  jekyll/_cci2/jobs-steps.md
  jekyll/_cci2/language-elixir.md
  jekyll/_cci2/local-cli.md
  jekyll/_cci2/migrating-from-1-2.md
  jekyll/_cci2/migrating-from-aws.adoc
  jekyll/_cci2/migrating-from-azuredevops.adoc
  jekyll/_cci2/migrating-from-buildkite.adoc
  jekyll/_cci2/migrating-from-gitlab.adoc
  jekyll/_cci2/migrating-from-travis.md
  jekyll/_cci2/optimization-cookbook.md
  jekyll/_cci2/optimizations.md
  jekyll/_cci2/overview.adoc
  jekyll/_cci2/parallelism-faster-jobs.md
  jekyll/_cci2/sample-config.md
  jekyll/_cci2/tutorials.md
  jekyll/_cci2/using-shell-scripts.md
  jekyll/_cci2/workflows-overview.md
  jekyll/_cci2/workflows.md
  jekyll/_cci2_ja/containers.md
  jekyll/_ccie/whycci.md
Labels: inconsistent

#4108 update asciidoctor and associated workflows
  .circleci/config.yml
  .gitignore
  Gemfile
  Gemfile.lock
  docs/server-docs-release-process.adoc
  jekyll/_cci2/_release-pdf/circle-theme.yml
  jekyll/_cci2/admin-faq.adoc
  jekyll/_cci2/architecture.adoc
  jekyll/_cci2/authentication.adoc
  jekyll/_cci2/aws-prereq.adoc
  jekyll/_cci2/aws-teardown.adoc
  jekyll/_cci2/aws.adoc
  jekyll/_cci2/backup.adoc
  jekyll/_cci2/build-artifacts.adoc
  jekyll/_cci2/certificates.adoc
  jekyll/_cci2/customizations.adoc
  jekyll/_cci2/gpu.adoc
  jekyll/_cci2/install-overview.adoc
  jekyll/_cci2/jvm-heap-size-configuration.adoc
  jekyll/_cci2/monitoring.adoc
  jekyll/_cci2/nomad-metrics.adoc
  jekyll/_cci2/nomad.adoc
  jekyll/_cci2/ops.adoc
  jekyll/_cci2/overview.adoc
  jekyll/_cci2/proxy.adoc
  jekyll/_cci2/security.adoc
  jekyll/_cci2/server-ports.adoc
  jekyll/_cci2/troubleshooting.adoc
  jekyll/_cci2/updating-server-replicated-version.adoc
  jekyll/_cci2/updating-server.adoc
  jekyll/_cci2/usage-stats.adoc
  jekyll/_cci2/user-accounts.adoc
  jekyll/_cci2/vm-service.adoc
  jekyll/_config.yml
  jekyll/_includes/snippets/server-unsupported.adoc
  package-lock.json
  scripts/build_pdfs_local.sh
Labels: dependencies
