Repository circleci/circleci-docs, pull requests merged in 2021-11, with the labels that each got.

#5879 [CIRCLE-38681]: Add property to Amplitude event to see which snippets are copied (Docs)
  src-js/experiments/highlightJSBadge.js
Labels: docs-disco

#5888 Server 3.2.1 release docs
  jekyll/_cci2/server-3-install-build-services.adoc
  jekyll/_cci2/server-3-install.adoc
  jekyll/_cci2/server-3-whats-new.adoc
  jekyll/_config.yml
Labels: Server v3.x

#5889 clarity in config ref
  jekyll/_cci2/configuration-reference.md
Labels: unclear

#5891 Add instructions for non-admin and admin requests
  jekyll/_cci2/gh-bb-integration.md
Labels: unclear

#5558 Add `orb-author-intro` link to te docs
  jekyll/_cci2/orb-author.md
Labels: external

#5892 Make container names consistent across machines
  docker-compose.yml
  package.json
Labels: docs-disco

#5881 [CIRCLE-38539] Add DataDog Synthetics Tests as CI Job
  .circleci/config.yml
  .datadog/development.synthetics.json
  .datadog/production.synthetics.json
  .gitignore
  package.json
  scripts/datadog-synthetics-ci.sh
  scripts/datadog-synthetics-preview.js
  scripts/postinstall.sh
  yarn.lock
Labels: docs-disco

#5836 [CIRCLE-38569] Migrate css styles to sass, imported with webpack
  .circleci/config.yml
  .github/CODEOWNERS
  .gitignore
  jekyll/_config.yml
  jekyll/_includes/head.html
  jekyll/assets/css/footer.css
  package.json
  src/js/app.js
  src/js/experiments/DevHubDocsNav.js
  src/js/experiments/forceAll.js
  src/js/experiments/highlightJSBadge.js
  src/js/experiments/relatedResources.js
  src/js/experiments/surfaceFullExampleConfig.js
  src/js/experiments/videoTutorials.js
  src/js/services/analytics.js
  src/js/services/analytics.test.js
  src/js/services/instantsearch.js
  src/js/services/lang.js
  src/js/services/optimizely.js
  src/js/site/main.js
  src/js/site/nav.js
  src/js/site/sidebar.js
  src/js/site/user.js
  src/js/utils.js
  src/js/vendor.js
  src/styles/_asciidoc.scss
  src/styles/_buttons.scss
  src/styles/_fonts.scss
  src/styles/_footer.scss
  src/styles/_global-nav.scss
  src/styles/_instantsearch.scss
  src/styles/_mobile.scss
  src/styles/_navgoco.scss
  src/styles/_sidebar.scss
  src/styles/_site.scss
  src/styles/_spacing.scss
  src/styles/_subnav.scss
  src/styles/_syntax-highlighting.scss
  src/styles/_syntax.scss
  src/styles/_tooltip.scss
  src/styles/_variables.scss
  src/styles/main.scss
  src/styles/shared
  webpack.config.js
  yarn.lock
Labels: docs-disco

#5893 [CIRCLE-38657] Adding H5 and H6 Headings to Side Nav in Docs
  jekyll/_config.yml
Labels: docs-disco

#5894 [CIRCLE-38658] Add DD rum integration
  package.json
  src/js/app.js
  src/js/services/rum.js
  src/js/services/rum.test.js
  src/js/utils.js
  src/js/utils.test.js
  yarn.lock
Labels: docs-disco

#5922 [WEB-549] Add alternate hreflang to all pages
  jekyll/_includes/head.html
Labels: docs-disco

#5917 Add webpack minification to js bundles
  package.json
  webpack.config.js
  yarn.lock
Labels: docs-disco

#5921 Fix: Add a `experimentContainer` to accurately track `Experiment Viewed` events
  src/js/experiments/DevHubDocsNav.js
  src/js/experiments/highlightJSBadge.js
  src/js/experiments/relatedResources.js
  src/js/experiments/surfaceFullExampleConfig.js
  src/js/experiments/videoTutorials.js
  src/js/services/optimizely.js
Labels: docs-disco

#5931 Chore: Remove `.idea/` folder
  .gitignore
  .idea/.gitignore
  .idea/circleci-docs.iml
  .idea/misc.xml
  .idea/modules.xml
Labels: docs-disco

#5916 [CIRCLE-38943] Rerun of related resource experiment with new position
  jekyll/_layouts/classic-docs.html
  src/js/experiments/relatedResources.js
Labels: docs-disco

#5926 [WEB-374] Update CTA Button in Docs Navbar per Latest Designs
  src/styles/_global-nav.scss
Labels: docs-disco

#5924 [CIRCLE-38942] - TOC highlight as you scroll.
  jekyll/_includes/edit-on-github.html
  jekyll/_includes/ja/edit-on-github.html
  jest/global.js
  src/js/site/sidebar.js
  src/js/site/sidebar.test.js
  src/js/utils.js
  src/js/utils.test.js
  src/styles/main.scss
Labels: docs-disco

#5964 [DD-6] Overflow issue on side nav
  src/styles/_sidebar.scss
Labels: docs-disco

#5959 [CIRCLE-38760] Add script to export data about snippets
  scripts/snippets_csv/.gitignore
  scripts/snippets_csv/README.md
  scripts/snippets_csv/index.js
  scripts/snippets_csv/package.json
  scripts/snippets_csv/yarn.lock
Labels: docs-disco
