Repository circleci/circleci-docs, pull requests merged in 2022-01, with the labels that each got.

#6124 [Fix] Grey left of sidebar on large width displays
  src/styles/_progressbar.scss
Labels: docs-disco

#6097 [DD-267]: Request New Language Form
  jekyll/_includes/global-nav.html
  jekyll/ja/index.html
  src/js/experiments/forceAll.js
  src/js/services/lang.js
  src/styles/_global-nav.scss
Labels: docs-disco

#6134 [DD-309] Remove old dateFormateAgo and switch to jekyll solution
  Gemfile
  Gemfile.lock
  jekyll/_config.yml
  jekyll/_layouts/classic-docs.html
  src/js/dateFormatAgoHelper.js
  src/js/dateFormatAgoHelper.test.js
  src/js/site/main.js
  src/styles/main.scss
Labels: docs-disco

#6024 Add missing sections to VM service guide
  jekyll/_cci2/server-3-install-build-services.adoc
  jekyll/_cci2/server-3-operator-vm-service.adoc
Labels: Server v3.x

#6067 [Server-1538] server 3.3 - Adding instructions for deploying nomad and vm-service in a shared VPC
  jekyll/_cci2/server-3-install-build-services.adoc
Labels: Server v3.x

#6066 [SERVER-1469] server 3.3 - adding docs for nomad-autoscaler on server
  jekyll/_cci2/server-3-install-build-services.adoc
Labels: Server v3.x

#6077 [DD-266] surface read time on the docs page
  jekyll/_config.yml
  jekyll/_includes/quick-info-list.html
  jekyll/_layouts/classic-docs.html
  src/styles/main.scss
Labels: docs-disco

#6176 Fix: Check for IntersectionObserver existence before using it
  src/js/site/sidebar.js
Labels: docs-disco

#6180 add in auth options for object storage
  jekyll/_cci2/server-3-install.adoc
Labels: Server v3.x

#6203 [Server 1543] - Adding instructions for generating roles for our 3.x server services
  jekyll/_cci2/server-3-install-build-services.adoc
  jekyll/_cci2/server-3-install.adoc
Labels: Server v3.x

#6096 Add mobile language selector
  jekyll/_includes/global-nav.html
  jekyll/_includes/lang_picker.html
  jekyll/_includes/utility-icons/globe.svg
  jekyll/assets/img/docs/arrow-green-right.svg
  jekyll/assets/img/docs/close.svg
  src/js/services/lang.js
  src/js/site/nav.js
  src/styles/_global-nav.scss
  src/styles/_langselector.scss
  src/styles/_utilities.scss
  src/styles/main.scss
Labels: docs-disco

#6220 [DD-333] Promote Article Suggester experiment
  jekyll/_config.yml
  jekyll/_layouts/classic-docs.html
  src-api/source/stylesheets/_rtl.scss
  src-api/source/stylesheets/screen.css.scss
  src/js/experiments/index.js
  src/js/experiments/relatedResources.js
  src/styles/_sidebar.scss
Labels: docs-disco

#6202 [DD-329]: Disable Search when Mobile Menu Open
  src/js/site/nav.js
Labels: docs-disco

#6170 Feat: Add a `yarn dev` cmd for local dev without Docker
  docs/local-development.md
  jekyll/_config.yml
  jekyll/_config_production.yml
  jekyll/_config_staging.yml
  package.json
  yarn.lock
Labels: docs-disco

#5797 Update references to legacy images
  jekyll/_cci2/artifactory.md
  jekyll/_cci2/building-docker-images.md
  jekyll/_cci2/code-coverage.md
  jekyll/_cci2/collect-test-data.md
  jekyll/_cci2/config-intro.md
  jekyll/_cci2/databases.md
  jekyll/_cci2/env-vars.md
  jekyll/_cci2/gh-bb-integration.md
  jekyll/_cci2/local-cli-getting-started.md
  jekyll/_cci2/migrating-from-github.adoc
  jekyll/_cci2/migrating-from-travis.md
  jekyll/_cci2/optimizations.md
  jekyll/_cci2/postgres-config.md
Labels: image update

#6235 Fix: Bring back DD synthetics tests for CI
  .datadog/development.synthetics.json
  .datadog/production.synthetics.json
Labels: docs-disco

#6214 [DD-332] Promote Surface Full Example Config
  jekyll/index.html
  src/js/experiments/index.js
  src/js/experiments/surfaceFullExampleConfig.js
  src/styles/main.scss
Labels: docs-disco

#6218 Miscellaneous changes made when working on Guided Tour
  src/js/experiments/snippetFeedback.js
  src/js/experiments/snippetFeedback.test.js
  src/js/experiments/videoTutorials.js
  src/js/services/progressbar.js
Labels: docs-disco

#6219 [DD-317] Add in hreflang Attribute
  src-api/source/layouts/layout.erb
  src-api/v2/template.hbs
Labels: docs-disco

#6145 server 3.3.0 docs release branch
  jekyll/_cci2/CircleCI-Server-3.3.0-Installation-Guide.pdf
  jekyll/_cci2/CircleCI-Server-3.3.0-Operations-Guide.pdf
  jekyll/_cci2/CircleCI-Server-3.3.0-Overview.pdf
  jekyll/_cci2/_release-pdf/circle-theme-install.yml
  jekyll/_cci2/private-images.adoc
  jekyll/_cci2/security-server.adoc
  jekyll/_cci2/server-3-faq.adoc
  jekyll/_cci2/server-3-install-build-services.adoc
  jekyll/_cci2/server-3-install-hardening-your-cluster.adoc
  jekyll/_cci2/server-3-install-migration.adoc
  jekyll/_cci2/server-3-install-post.adoc
  jekyll/_cci2/server-3-install-prerequisites.adoc
  jekyll/_cci2/server-3-install.adoc
  jekyll/_cci2/server-3-operator-application-lifecycle.adoc
  jekyll/_cci2/server-3-operator-authentication.adoc
  jekyll/_cci2/server-3-operator-backup-and-restore.adoc
  jekyll/_cci2/server-3-operator-build-artifacts.adoc
  jekyll/_cci2/server-3-operator-extending-internal-volumes.adoc
  jekyll/_cci2/server-3-operator-externalizing-services.adoc
  jekyll/_cci2/server-3-operator-load-balancers.adoc
  jekyll/_cci2/server-3-operator-metrics-and-monitoring.adoc
  jekyll/_cci2/server-3-operator-orbs.adoc
  jekyll/_cci2/server-3-operator-overview.adoc
  jekyll/_cci2/server-3-operator-proxy.adoc
  jekyll/_cci2/server-3-operator-troubleshooting-and-support.adoc
  jekyll/_cci2/server-3-operator-usage-data.adoc
  jekyll/_cci2/server-3-operator-user-accounts.adoc
  jekyll/_cci2/server-3-operator-vm-service.adoc
  jekyll/_cci2/server-3-overview.adoc
  jekyll/_cci2/server-3-upgrade.adoc
  jekyll/_cci2/server-3-whats-new.adoc
  jekyll/_cci2/webhooks.md
  jekyll/_config.yml
  jekyll/_data/sidenav.yml
  scripts/build_pdfs_asciidoc.sh
Labels: Server v3.x

#6221 [DD-334] Track if Users Enable Dark Mode
  src/js/app.js
  src/js/site/main.js
Labels: docs-disco

#6228 [DD-293] Fix header Nav Height when Expanded
  src/styles/_global-nav.scss
Labels: docs-disco

#6111 [DD-269] Node.JS & Python Guided Tours
  jekyll/_cci2/index.md
  jekyll/_cci2/language-javascript-experimental.md
  jekyll/_cci2/language-javascript.md
  jekyll/_cci2/language-python-experimental.md
  jekyll/_cci2/language-python.md
  jekyll/_config.yml
  jekyll/_includes/doc-footer.html
  jekyll/_includes/global-footer.html
  jekyll/_includes/no-script.html
  jekyll/_includes/snippets/language-card.md
  jekyll/_includes/snippets/language-guided-tour-cards.md
  jekyll/_layouts/classic-docs-experimental.html
  jekyll/_layouts/classic-docs.html
  jekyll/assets/img/compass/bookmark.svg
  jekyll/assets/img/compass/git-commit.svg
  jekyll/assets/img/compass/new.svg
  jekyll/assets/img/compass/nodejs.svg
  jekyll/assets/img/compass/python.svg
  jekyll/assets/img/compass/repo-forked.svg
  jekyll/index.html
  src/js/app.js
  src/js/experiments/index.js
  src/js/experiments/languageGuides.js
  src/js/site/index.js
  src/js/site/main.js
  src/js/site/sidebar.js
  src/js/site/sidebar.test.js
  src/js/site/toc.js
  src/js/site/toc.test.js
  src/js/utils.js
  src/styles/_language-guide.scss
  src/styles/_sidebar.scss
  src/styles/main.scss
  yarn.lock
Labels: docs-disco

#5997 migrating-from-teamcity-update
  jekyll/_cci2/migrating-from-teamcity.adoc
Labels: image update

#6000 hello world update
  jekyll/_cci2/hello-world.md
Labels: image update

#6012 example intro update
  jekyll/_cci2/examples-intro.md
Labels: image update

#6250 [DD-330]: Promote Share Button
  src/js/app.js
  src/js/services/index.js
  src/js/services/sectionShareButton.js
  src/js/site/main.js
Labels: docs-disco

#6272 [DD-318] Track if Users are Printing
  src/js/app.js
  src/js/site/main.js
Labels: docs-disco

#5996 java-maven legacy image update
  jekyll/_cci2/language-java-maven.md
Labels: image update

#5998 language-python-update
  jekyll/_cci2/language-python.md
Labels: image update

#6001 configuration reference update
  jekyll/_cci2/configuration-reference.md
Labels: image update

#6002 language java update
  jekyll/_cci2/language-java.md
Labels: image update

#6018 Update deployment-integrations.adoc
  jekyll/_cci2/deployment-integrations.adoc
Labels: image update

#6190 [DD-274] Add cypress e2e testing framework
  cypress.json
  cypress/integration/sidebar/sidebar.spec.js
  jekyll/_data/sidenav.yml
  jekyll/_includes/lang_picker.html
  jekyll/_includes/mobile-sidebar.html
  jekyll/_includes/sidebar.html
  jest.config.js
  package.json
  src/js/services/lang.js
  yarn.lock
Labels: docs-disco

#5828 Update images from circleci to cimg
  jekyll/_cci2/adv-config.md
  jekyll/_cci2/concepts.md
  jekyll/_cci2/language-elixir.md
  jekyll/_cci2/pipeline-variables.md
  jekyll/_cci2/reusing-config.md
Labels: image update

#6017 Update language-go.md
  jekyll/_cci2/language-go.md
Labels: image update

#6019 Update docker-layer-caching.md
  jekyll/_cci2/docker-layer-caching.md
Labels: image update

#6016 Update project-walkthrough.md
  jekyll/_cci2/project-walkthrough.md
Labels: image update

#6302 [FIX] Initialize lang.js when DOM is Loaded
  src/js/app.js
Labels: docs-disco

#6279 [DD-269] Node.JS & Python Guided Tours
  jekyll/_cci2/index.md
  jekyll/_cci2/language-javascript-experimental.md
  jekyll/_cci2/language-javascript.md
  jekyll/_cci2/language-python-experimental.md
  jekyll/_cci2/language-python.md
  jekyll/_config.yml
  jekyll/_includes/doc-footer.html
  jekyll/_includes/global-footer.html
  jekyll/_includes/no-script.html
  jekyll/_includes/snippets/language-card.md
  jekyll/_includes/snippets/language-guided-tour-cards.md
  jekyll/_layouts/classic-docs-experimental.html
  jekyll/_layouts/classic-docs.html
  jekyll/assets/img/compass/bookmark.svg
  jekyll/assets/img/compass/git-commit.svg
  jekyll/assets/img/compass/new.svg
  jekyll/assets/img/compass/nodejs.svg
  jekyll/assets/img/compass/python.svg
  jekyll/assets/img/compass/repo-forked.svg
  jekyll/index.html
  src/js/app.js
  src/js/experiments/index.js
  src/js/experiments/languageGuides.js
  src/js/site/index.js
  src/js/site/main.js
  src/js/site/sidebar.js
  src/js/site/sidebar.test.js
  src/js/site/toc.js
  src/js/site/toc.test.js
  src/js/utils.js
  src/styles/_language-guide.scss
  src/styles/_sidebar.scss
  src/styles/main.scss
Labels: docs-disco

#5999 language-clojure-update
  jekyll/_cci2/language-clojure.md
Labels: image update

#6141 Brian's updates
  jekyll/_cci2/browser-testing.md
  jekyll/_cci2/getting-started.md
  jekyll/_cci2/language-android.md
  jekyll/_cci2/language-php.md
  jekyll/_cci2/language-ruby.md
  jekyll/_cci2/packagecloud.md
  jekyll/_cci2/sample-config.md
  jekyll/_cci2/triggers.md
Labels: image update
