Repository circleci/circleci-docs, pull requests merged in 2022-04, with the labels that each got.

#6644 [Dd 455] - homepage redesign preview
  jekyll/_cci2/index.md
  jekyll/_includes/badge.html
  jekyll/assets/img/compass/circle-logo.svg
  jekyll/assets/img/compass/more.svg
  src/js/experiments/gettingStartedGuide.js
  src/styles/_first_steps_cta.scss
  src/styles/_popup.scss
  src/styles/_utilities.scss
  src/styles/includes/_badge.scss
  src/styles/main.scss
  src/styles/mixins/_cta_badge.scss
  src/styles/pages/_getting-started.scss
Labels: docs-disco

#6631 Fixed typo in yarn.md
  jekyll/_cci2_ja/yarn.md
Labels: l10n japanese

#6661 Use cimg/* images for example on /variables/
  jekyll/_cci2/variables.md
Labels: external

#6650 [DD-456] Finalize Getting Started Experiment
  jekyll/_cci2/getting-started-guide-experimental.md
  jekyll/_cci2/getting-started.md
  jekyll/_includes/getting-started-links.html
  jekyll/_includes/getting-started-section-header.html
  jekyll/_includes/vcs-banner.html
  jekyll/_layouts/getting-started-guide-experimental.html
  jekyll/assets/img/docs/getting-started-guide-exp/CCI-config-editor.png
  jekyll/assets/img/docs/getting-started-guide-exp/SSH-into-build.png
  jekyll/assets/img/docs/getting-started-guide-exp/break-your-build.png
  jekyll/assets/img/docs/getting-started-guide-exp/collab-with-team.png
  jekyll/assets/img/docs/getting-started-guide-exp/congrats-first-green-pipeline.png
  jekyll/assets/img/docs/getting-started-guide-exp/explore-workflows.png
  jekyll/assets/img/docs/getting-started-guide-exp/quick-start--first-step.svg
  jekyll/assets/img/docs/getting-started-guide-exp/quick-start--second-step.svg
  jekyll/assets/img/docs/getting-started-guide-exp/quick-start--third-step.svg
  jekyll/assets/img/docs/getting-started-guide-exp/select-config.png
  jekyll/assets/img/docs/getting-started-guide-exp/select-project.png
  jekyll/assets/img/docs/getting-started-guide-exp/view-results.png
  jekyll/assets/img/docs/getting-started-guide-exp/what-just-happened.png
  src/js/experiments/gettingStartedGuide.js
  src/styles/includes/getting-started-prereq.scss
  src/styles/includes/two-up.scss
  src/styles/main.scss
Labels: docs-disco

#6613 Update environment variables
  jekyll/_cci2/ecs-ecr.md
Labels: external

#6647 add 20.10.12 to list of available docker versions
  jekyll/_cci2/building-docker-images.md
Labels: external

#6635 Remove unsupported key 'when' from store_artifacts
  jekyll/_cci2/language-java.md
Labels: external

#6688 [DD-545] Permanent Push: Update the Sign-up CTA button verbiage
  jekyll/_includes/global-nav.html
  src/js/experiments/index.js
  src/js/experiments/signUpCTA.js
Labels: docs-disco

#6691 [DD-546] Permanent Push: Add Sign-up CTA to docs/2.0/first-steps
  jekyll/_cci2/first-steps.md
  jekyll/_cci2_ja/first-steps.md
  src/js/experiments/index.js
  src/js/experiments/signupLinksCta.js
  src/js/site/main.js
  src/styles/_first_steps_cta.scss
Labels: docs-disco

#6544 [DD-450] Getting Started Experiment Boilerplate
  jekyll/_cci2/getting-started-guide-experimental.md
  jekyll/_cci2/getting-started.md
  jekyll/_cci2/index.md
  jekyll/_includes/badge.html
  jekyll/_includes/getting-started-links.html
  jekyll/_includes/getting-started-section-header.html
  jekyll/_includes/vcs-banner.html
  jekyll/_layouts/classic-docs.html
  jekyll/_layouts/getting-started-guide-experimental.html
  jekyll/assets/img/compass/circle-logo.svg
  jekyll/assets/img/compass/more.svg
  jekyll/assets/img/docs/getting-started-guide-exp/CCI-config-editor.png
  jekyll/assets/img/docs/getting-started-guide-exp/SSH-into-build.png
  jekyll/assets/img/docs/getting-started-guide-exp/break-your-build.png
  jekyll/assets/img/docs/getting-started-guide-exp/collab-with-team.png
  jekyll/assets/img/docs/getting-started-guide-exp/congrats-first-green-pipeline.png
  jekyll/assets/img/docs/getting-started-guide-exp/explore-workflows.png
  jekyll/assets/img/docs/getting-started-guide-exp/quick-start--first-step.svg
  jekyll/assets/img/docs/getting-started-guide-exp/quick-start--second-step.svg
  jekyll/assets/img/docs/getting-started-guide-exp/quick-start--third-step.svg
  jekyll/assets/img/docs/getting-started-guide-exp/select-config.png
  jekyll/assets/img/docs/getting-started-guide-exp/select-project.png
  jekyll/assets/img/docs/getting-started-guide-exp/view-results.png
  jekyll/assets/img/docs/getting-started-guide-exp/what-just-happened.png
  src/js/experiments/gettingStartedGuide.js
  src/js/experiments/index.js
  src/js/site/toc.js
  src/styles/_first_steps_cta.scss
  src/styles/_popup.scss
  src/styles/_utilities.scss
  src/styles/includes/_badge.scss
  src/styles/includes/getting-started-prereq.scss
  src/styles/includes/two-up.scss
  src/styles/main.scss
  src/styles/mixins/_cta_badge.scss
  src/styles/pages/_getting-started.scss
Labels: docs-disco

#6716 [DD-542] Inline API v1 resources
  src-api/config.rb
  src-api/lib/middleman-inline.rb
  src-api/source/layouts/layout.erb
Labels: docs-disco

#6733 Avoid POSTGRES_USER=root env on /configuration-reference
  jekyll/_cci2/configuration-reference.md
Labels: external

#6734 Avoid POSTGRES_USER=root env on /postgres-config
  jekyll/_cci2/postgres-config.md
Labels: external

#6735 Avoid POSTGRES_USER=root env on /project-walkthrough
  jekyll/_cci2/project-walkthrough.md
Labels: external

#6738 oss: Relay does not use CircleCI any more
  jekyll/_cci2/oss.md
Labels: external

#6732 Avoid POSTGRES_USER=root env and old postgres image tags
  jekyll/_cci2/concepts.md
Labels: external

#6751 Replace buildpack-deps with cimg/base:2022.04-20.04 on /concepts
  jekyll/_cci2/concepts.md
Labels: external
