Repository circleci/circleci-docs, pull requests merged in 2023-01, with the labels that each got.

#7677 Update CODEOWNERS
  .github/CODEOWNERS
Labels: cf2023-codeowners-update

#6805 Add example for how to ignore for Review
  jekyll/_cci2/testing-orbs.md
Labels: external

#7682 Add Xcode 14.2.0 on Japanese translation
  jekyll/_includes/snippets/ja/xcode-intel-vm.md
Labels: Japanese, external
